import type {
	InstalledMod,
	ModListFile,
	WorkshopUpdateCheckResult,
} from '@/utils/types';

type TestModListFixture = {
	installedMods: InstalledMod[];
	modList: ModListFile;
	updateCheckResult: WorkshopUpdateCheckResult;
};

export const TEST_MOD_LIST: TestModListFixture = {
	installedMods: [
		{
			name: 'Core',
			author: null,
			modVersion: null,
			packageId: 'ludeon.rimworld',
			description: 'Base game content used by the sample list.',
			publishedFileId: null,
			loadAfter: [],
			loadBefore: [],
			incompatibleWith: [],
			supportedVersions: ['1.6'],
			versionWarningSilenced: false,
			path: 'Sample data/Core',
			source: 'game',
			dependencies: [],
		},
		{
			name: 'RimWorld - Royalty',
			author: null,
			modVersion: null,
			packageId: 'ludeon.rimworld.royalty',
			description: 'Official RimWorld expansion content.',
			publishedFileId: null,
			loadAfter: ['ludeon.rimworld'],
			loadBefore: [],
			incompatibleWith: [],
			supportedVersions: ['1.6'],
			versionWarningSilenced: false,
			path: 'Sample data/Royalty',
			source: 'game',
			dependencies: [],
		},
		{
			name: 'RimWorld - Biotech',
			author: null,
			modVersion: null,
			packageId: 'ludeon.rimworld.biotech',
			description: 'Official RimWorld expansion content.',
			publishedFileId: null,
			loadAfter: ['ludeon.rimworld'],
			loadBefore: [],
			incompatibleWith: [],
			supportedVersions: ['1.6'],
			versionWarningSilenced: false,
			path: 'Sample data/Biotech',
			source: 'game',
			dependencies: [],
		},
		{
			name: 'Harmony',
			author: 'Brrainz',
			modVersion: null,
			packageId: 'brrainz.harmony',
			description: 'A sample framework mod.',
			publishedFileId: null,
			loadAfter: ['ludeon.rimworld'],
			loadBefore: [],
			incompatibleWith: [],
			supportedVersions: ['1.6'],
			versionWarningSilenced: false,
			path: 'Sample data/Mods/Harmony',
			source: 'local',
			dependencies: [],
		},
		{
			name: 'Sample Framework',
			author: null,
			modVersion: null,
			packageId: 'sample.framework',
			description:
				'Drag this framework into Active to resolve the sample dependency warning.',
			publishedFileId: null,
			loadAfter: ['brrainz.harmony'],
			loadBefore: ['sample.vehiclemod'],
			incompatibleWith: [],
			supportedVersions: ['1.6'],
			versionWarningSilenced: false,
			path: 'Sample data/Mods/SampleFramework',
			source: 'local',
			dependencies: [],
		},
		{
			name: 'Sample Vehicle Mod',
			author: null,
			modVersion: null,
			packageId: 'sample.vehiclemod',
			description:
				'This sample intentionally has a missing framework dependency. Use it to exercise active-mod diagnostics.',
			publishedFileId: null,
			loadAfter: ['sample.framework'],
			loadBefore: [],
			incompatibleWith: [],
			supportedVersions: ['1.6'],
			versionWarningSilenced: false,
			path: 'Sample data/Mods/SampleVehicleMod',
			source: 'local',
			dependencies: [
				{
					packageId: 'sample.framework',
					name: 'Sample Framework',
					alternativePackageIds: [],
				},
			],
		},
		{
			name: 'Sample Patch Pack',
			author: null,
			modVersion: null,
			packageId: 'sample.patchpack',
			description:
				'A second inactive sample mod for search and drag-and-drop testing.',
			publishedFileId: null,
			loadAfter: ['sample.vehiclemod'],
			loadBefore: [],
			incompatibleWith: [],
			supportedVersions: ['1.6'],
			versionWarningSilenced: false,
			path: 'Sample data/Mods/SamplePatchPack',
			source: 'local',
			dependencies: [],
		},
	],
	modList: {
		version: '1.6',
		activeMods: [
			'ludeon.rimworld',
			'ludeon.rimworld.royalty',
			'brrainz.harmony',
			'sample.vehiclemod',
		],
		knownExpansions: [
			'ludeon.rimworld.royalty',
			'ludeon.rimworld.biotech',
		],
	},
	updateCheckResult: {
		checkedCount: 1,
		skippedCount: 0,
		outdatedMods: [
			{
				name: 'Sample Vehicle Mod',
				packageId: 'sample.vehiclemod',
				publishedFileId: '123456789',
				installedTimeUpdated: 1700000000,
				steamTimeUpdated: 1700000100,
			},
		],
	},
};
