name: Code Quality

on:
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    code-quality:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
            - name: Set up Deno
              uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
            - name: Set up Rust
              uses: dtolnay/rust-toolchain@stable
            - name: Install Tauri Linux dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install --no-install-recommends -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
            - name: Check Knip
              run: deno task knip
            - name: Check formatting
              run: deno task format
            - name: Lint
              run: deno task lint
            - name: Build Tauri application
              run: deno task tauri build
